version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data:z
    networks:
      - scheduler-net
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    networks:
      - scheduler-net
  backend:
    build:
      context: .
    image: ${DOCKER_HUB_REPO}/scheduler-be:${DOCKER_TAG}
    container_name: backend
    environment:
      - ENV=dev
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@postgres:5432
    ports:
      - "8080:8080"
    networks:
      - scheduler-net
    depends_on:
      - postgres
      - redis
networks:
  scheduler-net:
    driver: bridge
